# The content of this file was generated by IBM Cloud
# Do not modify it as it might get overridden

from ibmcloudenv import IBMCloudEnv
from . import service_manager
IBMCloudEnv.init()

from . import service_watson_conversation


def initServices(app):
	
	name, service = service_watson_conversation.getService(app)
	service_manager.set(name, service)

	return
